# a conda env
name: pyb2d
channels:
  - conda-forge
dependencies:
  # Build tools
  - cxx-compiler
  - c-compiler
  - cmake
  - ninja
  - scikit-build-core
  - uv
  # build deps
  - python >=3.13
  - nanobind
  - box2d >=3.1.1
  # run deps
  - numpy
  # Tests
  - pytest
  - pytest-sugar√•
  # utils
  - pre-commit
  # frontend
  - pygame
  # docs
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-video
  - sphinx-design
  - ffmpeg
